/* ---- 語彙 ----
   本番は英語受験なので、読めないと知識があっても落ちる。
   ここに載る例語・用例は、すべて上の137問の本文から採っている（作った例文は無い）。
   ex の数字はこの問題集の中での出現回数。 */
const VOCAB = {

prefix: [
  { a:'sub-',    ja:'下に・下位の',   note:'上位のものにぶら下がる感じ。組織図の下の段。', ex:['subagent','subsequent','subtopic','submit'] },
  { a:'de-',     ja:'離す・下へ・完全に', note:'3つの意味が同居する。離す（delegate 委ねる）、下へ（degrade 落ちる）、完全に（determine 完全に境界を引く＝決める）。', ex:['delegate','degradation','decomposition','deterministic','detection'] },
  { a:'re-',     ja:'再び・後ろへ',   note:'もう一度（retry）と、元へ戻す（resolve ほどき戻す）の両方。', ex:['retry','resolution','recovery','reference','regardless'] },
  { a:'pre-',    ja:'前に',           note:'時間の前。prerequisite は「前に要求されるもの」。', ex:['prerequisite','prevent','precede','present'] },
  { a:'pro-',    ja:'前へ・先へ',     note:'pre- が「時間の前」なら pro- は「前方へ出る」動き。', ex:['provenance','propagate','produce','process','proceed'] },
  { a:'in- / im-', ja:'中へ／否定',   note:'同じ綴りで正反対。invoke は中へ呼ぶ、invalid は valid でない。後ろの語が名詞なら中へ、形容詞なら否定のことが多い。', ex:['invoke','intermediate','invalid','inconsistent'] },
  { a:'con- / com-', ja:'共に・一緒に', note:'集める・そろえる感じ。consistent は「一緒に立っている」＝ぶれない。', ex:['consistent','compliance','compression','constraints','concerns'] },
  { a:'ex-',     ja:'外へ',           note:'explicit は「外に折り出された」＝はっきり出ている。暗黙 implicit の対。', ex:['explicit','exploration','extraction','execution','exceed'] },
  { a:'trans-',  ja:'越えて・移って', note:'transient は「通り過ぎていく」＝一時的な。', ex:['transient','transfer','transport'] },
  { a:'inter-',  ja:'間に',           note:'2つのものの間。intermediate は「中間の」。', ex:['intermediate','interception','intelligence'] },
  { a:'dis-',    ja:'離す・分ける・否定', note:'discovery は「覆い dis-cover を外す」＝発見。distinction は分けること。', ex:['discovery','distinction','distinguish','dispute'] },
  { a:'per-',    ja:'通して・ずっと', note:'persistent は「ずっと立っている」＝居続ける。', ex:['persistent','permission','performance'] },
  { a:'ad- / at-', ja:'〜の方へ',     note:'後ろの子音に合わせて形が変わる（ad + tribute → attribute）。attribution は「〜のせいだと帰する」こと。', ex:['attribution','adaptive','address','attempt'] },
  { a:'auto-',   ja:'自分で・自動で', note:'autonomous は「自分で法を持つ」＝自律的。', ex:['automatically','autonomous','automation'] },
  { a:'multi-',  ja:'多い・複数の',   note:'multi-issue は「論点が複数の」。', ex:['multi-issue','multiple','multi-turn'] },
  { a:'non-',    ja:'〜でない',       note:'中立的な否定。non-empty は「空でない」。', ex:['non-empty','non-blocking','non-interactive'] },
  { a:'over-',   ja:'上に・過剰に',   note:'overhead は「頭の上にのしかかる分」＝間接費・余分な負荷。', ex:['overhead','override','oversized','overwhelmed'] },
  { a:'under-',  ja:'下に',           note:'underlying は「下に横たわる」＝根底にある。', ex:['underlying','understand'] },
  { a:'post-',   ja:'後で',           note:'pre- の対。post-processing は「後処理」。', ex:['post-processing','postpones','post-synthesis'] },
  { a:'mis-',    ja:'誤って',         note:'misread は読み違い。批判の語に多い。', ex:['misread','misuse','mismatch','misclassify'] },
  { a:'counter-',ja:'逆に・対抗して', note:'counterexample は「反例」。', ex:['counterexample','counterpart'] },
  { a:'un-',     ja:'〜でない・戻す', note:'形容詞の否定（unreliable）と動作の取り消し（undo）。', ex:['unreliable','unambiguous','unconstrained','undo'] },
  { a:'semi-',   ja:'半分・やや',     note:'semi-structured は「半構造化の」。', ex:['semi-structured'] },
  { a:'co-',     ja:'共同で',         note:'coordinator は「一緒に順序づける人」＝取りまとめ役。', ex:['coordinator','correlate','coherent'] }
],

suffix: [
  { a:'-tion / -sion', ja:'〜すること（動作の名詞）', note:'動詞を名詞にする最頻の形。validate → validation。', ex:['validation','isolation','decomposition','invocation','compression'] },
  { a:'-ment',   ja:'〜すること・〜したもの', note:'-tion より結果物寄り。judgment は「判断したもの」。', ex:['judgment','enforcement','requirement','assignment'] },
  { a:'-ance / -ence', ja:'〜である状態', note:'compliance は「従っている状態」。', ex:['compliance','provenance','reference','difference'] },
  { a:'-ity / -ility', ja:'〜であること（性質）', note:'形容詞を名詞に。capable → capability、granular → granularity。', ex:['capability','granularity','complexity','reliability'] },
  { a:'-ness',   ja:'〜さ（性質）',   note:'-ity がラテン語系なのに対しこちらはゲルマン語系。', ex:['completeness','correctness','robustness'] },
  { a:'-ous',    ja:'〜の性質を持つ（形容詞）', note:'ambiguous は「両方へ ambi- 進む ag- 性質」＝どちらとも取れる。', ex:['ambiguous','autonomous','verbose(-ose)'] },
  { a:'-ive',    ja:'〜する傾向がある（形容詞）', note:'adaptive は「適応する性質の」。', ex:['adaptive','iterative','effective','comprehensive'] },
  { a:'-able / -ible', ja:'〜できる', note:'retryable は「再試行できる」。造語しやすいので新語がよく出る。', ex:['retryable','plausible','feasible','traceable'] },
  { a:'-al',     ja:'〜に関する（形容詞）', note:'structural は「構造に関する」。', ex:['structural','architectural','sequential','incremental'] },
  { a:'-ic / -istic', ja:'〜的な',    note:'deterministic は「決定する性質の」。', ex:['deterministic','systematic','dynamic','static'] },
  { a:'-ate',    ja:'〜にする（動詞）／〜された（形容詞）', note:'動詞と形容詞で発音が変わる。delegate（デリゲイト＝委ねる）と intermediate（インターミディエット＝中間の）。', ex:['delegate','escalate','calibrate','aggregate','intermediate'] },
  { a:'-ify / -ize', ja:'〜にする（動詞）', note:'specify は「specific にする」＝明示する。', ex:['specify','verify','normalize','summarize'] },
  { a:'-ly',     ja:'〜のように（副詞）', note:'precisely、silently。文の意味を反転させることがあるので読み飛ばさない。', ex:['precisely','silently','explicitly','simultaneously'] },
  { a:'-er / -or', ja:'〜する人・もの', note:'coordinator、reviewer。エージェント設計では「役割の名前」として頻出。', ex:['coordinator','reviewer','developer','parameter'] },
  { a:'-ency / -ancy', ja:'〜である性質', note:'dependency は「依存している状態」。', ex:['dependency','consistency','latency','redundancy'] },
  { a:'-less',   ja:'〜が無い',       note:'regardless は「顧みる regard ことが無い」＝〜に関わらず。', ex:['regardless','stateless','seamless'] },
  { a:'-ful',    ja:'〜に満ちた',     note:'successful は「成功に満ちた」。', ex:['successful','graceful','meaningful'] },
  { a:'-wise',   ja:'〜の観点で',     note:'otherwise は「他のやり方では」＝さもなければ。', ex:['otherwise','likewise'] }
],

roots: [
  { r:'term / termin', ja:'境界・終わり', note:'terminal（終点）と同じ根。境界を引く＝決める。',
    fam:[{w:'deterministic',lit:'完全に de- 境界が決まっている',ja:'決定論的な'},{w:'terminate',lit:'終わりにする',ja:'終了させる'},{w:'termination',lit:'終わらせること',ja:'終了'},{w:'determine',lit:'完全に境界を引く',ja:'決定する'}] },
  { r:'sequ / secut', ja:'続く・後を追う', note:'「順番に続いていく」。',
    fam:[{w:'sequential',lit:'続いていく',ja:'逐次の'},{w:'subsequent',lit:'下に続く',ja:'後続の'},{w:'sequence',lit:'続き',ja:'順序・並び'},{w:'consequence',lit:'一緒に続いて起きること',ja:'帰結'}] },
  { r:'struct', ja:'積み上げる・建てる', note:'construction（建設）と同根。instruction は「中へ積む」＝教え込むこと。',
    fam:[{w:'structured',lit:'組み立てられた',ja:'構造化された'},{w:'structural',lit:'構造に関する',ja:'構造的な'},{w:'instruction',lit:'中へ積む',ja:'指示'},{w:'construct',lit:'共に積む',ja:'構文・構造物'}] },
  { r:'sist / sta / st', ja:'立つ', note:'stand と同じ。「その場に立っている」イメージ。',
    fam:[{w:'consistent',lit:'一緒に立っている',ja:'一貫した'},{w:'persistent',lit:'ずっと立っている',ja:'永続的な'},{w:'inconsistent',lit:'一緒に立てていない',ja:'ばらつく'},{w:'status',lit:'立っている状態',ja:'状態'},{w:'instance',lit:'そばに立つもの',ja:'実体・個体'}] },
  { r:'val', ja:'価値がある・強い', note:'value と同じ。valid は「効力が立っている」。',
    fam:[{w:'validation',lit:'効力があると確かめること',ja:'検証'},{w:'valid',lit:'効力がある',ja:'妥当な'},{w:'invalid',lit:'効力がない',ja:'無効な'},{w:'evaluate',lit:'外へ価値を出す',ja:'評価する'}] },
  { r:'solv / solu', ja:'ほどく・解く', note:'結び目をほどく。resolve は「もう一度ほどく」＝解決する。',
    fam:[{w:'resolve',lit:'ほどき戻す',ja:'解決する'},{w:'resolution',lit:'ほどくこと',ja:'解決・解像度'},{w:'solution',lit:'解かれたもの',ja:'解決策'}] },
  { r:'press', ja:'押す', note:'圧をかける。compression は「一緒に押し込む」。',
    fam:[{w:'compression',lit:'一緒に押し込むこと',ja:'圧縮'},{w:'suppress',lit:'下へ押さえる',ja:'抑え込む'},{w:'express',lit:'外へ押し出す',ja:'表現する・明示の'}] },
  { r:'scrib / script', ja:'書く', note:'description は「下へ書き下したもの」＝説明。',
    fam:[{w:'description',lit:'下へ書く',ja:'説明文'},{w:'describe',lit:'下へ書く',ja:'記述する'},{w:'script',lit:'書かれたもの',ja:'台本・スクリプト'}] },
  { r:'cap / cip / cept', ja:'つかむ・取る', note:'capacity は「取れる量」。intercept は「間で取る」＝横取りする。',
    fam:[{w:'capability',lit:'取れること',ja:'能力・機能'},{w:'capacity',lit:'取れる量',ja:'容量'},{w:'capture',lit:'つかむ',ja:'捕える'},{w:'intercept',lit:'間でつかむ',ja:'横取りする'}] },
  { r:'port', ja:'運ぶ', note:'港 port は「運び込む場所」。report は「後ろへ運ぶ」＝持ち帰って伝える。',
    fam:[{w:'report',lit:'後ろへ運ぶ',ja:'報告する'},{w:'transport',lit:'越えて運ぶ',ja:'転送・輸送'},{w:'support',lit:'下から運ぶ',ja:'支える'},{w:'important',lit:'中へ運び込む',ja:'重要な'}] },
  { r:'ven / vent', ja:'来る', note:'provenance は「前から来たもの」＝どこから来たかの記録。',
    fam:[{w:'provenance',lit:'前から来ること',ja:'来歴・出所'},{w:'prevent',lit:'前に来て立ちふさがる',ja:'防ぐ'},{w:'event',lit:'外へ出てくるもの',ja:'出来事'}] },
  { r:'tain / ten', ja:'保つ・持つ', note:'contain は「一緒に持つ」＝含む。',
    fam:[{w:'maintain',lit:'手で保つ',ja:'保守する'},{w:'contain',lit:'一緒に持つ',ja:'含む'},{w:'content',lit:'中に持たれたもの',ja:'中身'},{w:'retain',lit:'後ろへ保つ',ja:'保持する'}] },
  { r:'spec / spect', ja:'見る', note:'inspect は「中を見る」。specific は「見分けられた」＝特定の。',
    fam:[{w:'specific',lit:'見分けられた',ja:'特定の・具体的な'},{w:'specify',lit:'見分けられるようにする',ja:'明示する'},{w:'aspect',lit:'〜の方を見た姿',ja:'観点'},{w:'inspect',lit:'中を見る',ja:'検査する'}] },
  { r:'fer', ja:'運ぶ・もたらす', note:'reference は「後ろへ運んで戻す」＝参照。infer は「中へ運び込む」＝推論する。',
    fam:[{w:'reference',lit:'後ろへ運び戻すもの',ja:'参照'},{w:'transfer',lit:'越えて運ぶ',ja:'移す'},{w:'infer',lit:'中へ運び込む',ja:'推論する'},{w:'different',lit:'離して運ぶ',ja:'異なる'}] },
  { r:'duc / duct', ja:'導く', note:'produce は「前へ導き出す」＝生み出す。',
    fam:[{w:'produce',lit:'前へ導き出す',ja:'生み出す'},{w:'reduce',lit:'後ろへ導く',ja:'減らす'},{w:'introduce',lit:'中へ導き入れる',ja:'導入する'},{w:'production',lit:'生み出すこと',ja:'本番・生産'}] },
  { r:'ject', ja:'投げる', note:'reject は「投げ返す」。project は「前へ投げる」＝計画・投影。',
    fam:[{w:'reject',lit:'投げ返す',ja:'却下する'},{w:'project',lit:'前へ投げる',ja:'計画・投影する'},{w:'object',lit:'向かって投げられたもの',ja:'対象・異議を唱える'}] },
  { r:'cede / cess', ja:'行く・進む', note:'process は「前へ進むこと」。exceed は「外へ出て行く」＝超える。',
    fam:[{w:'process',lit:'前へ進むこと',ja:'処理・工程'},{w:'exceed',lit:'外へ出て行く',ja:'超える'},{w:'precede',lit:'前を行く',ja:'先立つ'},{w:'access',lit:'〜へ行くこと',ja:'アクセス'}] },
  { r:'grad / gress', ja:'歩む・段', note:'grade（段階）と同じ。degradation は「段を下る」＝劣化。',
    fam:[{w:'degradation',lit:'段を下ること',ja:'劣化'},{w:'degrade',lit:'段を下る',ja:'劣化する'},{w:'aggregate',lit:'群れへ寄せ集める',ja:'集計する・全体の'}] },
  { r:'mit / miss', ja:'送る・放つ', note:'submit は「下へ送る」＝提出する。omit は「外へ送る」＝省く。',
    fam:[{w:'submit',lit:'下へ送る',ja:'提出する'},{w:'omit',lit:'外へ送る',ja:'省く'},{w:'emit',lit:'外へ放つ',ja:'発する'},{w:'permission',lit:'通して送ることを許すこと',ja:'許可'}] },
  { r:'pend / pens', ja:'掛ける・吊るす', note:'depend は「下に吊るされている」＝頼っている。',
    fam:[{w:'depend',lit:'下に吊るされる',ja:'依存する'},{w:'dependency',lit:'吊るされている状態',ja:'依存関係'},{w:'independent',lit:'吊るされていない',ja:'独立した'},{w:'expensive',lit:'外へ量り出す',ja:'高価な'}] },
  { r:'leg / lect', ja:'選ぶ・読む', note:'select は「離して選ぶ」。collect は「一緒に集める」。',
    fam:[{w:'select',lit:'離して選ぶ',ja:'選ぶ'},{w:'selection',lit:'選ぶこと',ja:'選択'},{w:'collect',lit:'一緒に集める',ja:'集める'},{w:'intelligence',lit:'間から選び取る力',ja:'知能・情報'}] },
  { r:'fac / fic / fect', ja:'作る・なす', note:'effective は「外へなし遂げる」＝効果のある。',
    fam:[{w:'effective',lit:'外へなし遂げる',ja:'効果のある'},{w:'efficient',lit:'手際よくなす',ja:'効率的な'},{w:'verification',lit:'真 ver- を作ること',ja:'検証'},{w:'artefact',lit:'技で作られたもの',ja:'成果物・産物'}] },
  { r:'cur / curs', ja:'走る', note:'current は「いま走っている」＝現在の・流れ。occur は「向かって走ってくる」＝起きる。',
    fam:[{w:'current',lit:'いま走っている',ja:'現在の'},{w:'occur',lit:'向かって走ってくる',ja:'起きる'},{w:'concurrent',lit:'一緒に走る',ja:'並行の'},{w:'recur',lit:'また走る',ja:'再発する'}] }
],
